[tool.poetry]
name = "guitar-game"
version = "0.1.0"
description = ""
authors = ["theplatecrafter <theplatecrater@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pyo = "^1.0.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
